export const emailId="manishpandey1316@gmail.com"
export const linkdeinProfile="https://www.linkedin.com/in/manishpandeybhu"
export const githubProfile="https://github.com/manishpandey1316"
export const codechefProfile="https://www.codechef.com/users/manishpandey13"
export const leetcodeProfile="https://leetcode.com/MANISHPANDEY1316/"
